name: jus_mobile_order_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.1.1
  firebase_remote_config: ^4.0.2
  cloud_functions: ^4.0.5
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  pay: ^1.1.0
  square_in_app_payments: ^1.7.5
  animations: ^2.0.7
  permission_handler: ^10.2.0
  intl: ^0.17.0
  google_fonts: ^4.0.1
  encrypt: ^5.0.1
  cached_network_image: ^3.2.3
  top_modal_sheet: ^2.0.1
  flutter_emoji: ^2.4.0
  font_awesome_flutter: ^10.3.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.2.2
  maps_launcher: ^2.0.1
  geolocator: ^9.0.2
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.8
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.0
  visibility_detector: ^0.3.3
  email_validator: ^2.1.17
  simple_grouped_listview: ^2.0.0
  collection: ^1.16.0
  badges: ^3.0.2
  flip_card: ^0.7.0
  credit_card_validator: ^2.0.1
  qr_flutter: ^4.0.0
  flutter_calendar_carousel: ^2.4.1
  confetti: ^0.7.0
  add_2_calendar: ^2.2.3
  us_states: ^1.2.0

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/jus_logo_splash.png'

dev_dependencies:
  build_runner:
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/jus_logo_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/jus_logo_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/jus_logo_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/jus_logo_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - google_fonts/