// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnybhudr10-A3Lq5oAVH4ERVgvzdVmEoE',
    appId: '1:375720547393:web:fdf42e42142c91afd562c0',
    messagingSenderId: '375720547393',
    projectId: 'jusmobileorderapp',
    authDomain: 'jusmobileorderapp.firebaseapp.com',
    storageBucket: 'jusmobileorderapp.appspot.com',
    measurementId: 'G-FBLESBNQXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfA_ghFLu1Ke5T7R9OxzdfyuypS4OWyaI',
    appId: '1:375720547393:android:1621a6ac079acc19d562c0',
    messagingSenderId: '375720547393',
    projectId: 'jusmobileorderapp',
    storageBucket: 'jusmobileorderapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy9JwhocAhGgH6dN6Tl7W0JJ1WFmJRVOs',
    appId: '1:375720547393:ios:356b0dea7a0fe0a5d562c0',
    messagingSenderId: '375720547393',
    projectId: 'jusmobileorderapp',
    storageBucket: 'jusmobileorderapp.appspot.com',
    iosClientId: '375720547393-oi3l9cfkgkn9rjid3aodh5raig5n2e8b.apps.googleusercontent.com',
    iosBundleId: 'com.jusreno.jusMobileOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy9JwhocAhGgH6dN6Tl7W0JJ1WFmJRVOs',
    appId: '1:375720547393:ios:356b0dea7a0fe0a5d562c0',
    messagingSenderId: '375720547393',
    projectId: 'jusmobileorderapp',
    storageBucket: 'jusmobileorderapp.appspot.com',
    iosClientId: '375720547393-oi3l9cfkgkn9rjid3aodh5raig5n2e8b.apps.googleusercontent.com',
    iosBundleId: 'com.jusreno.jusMobileOrderApp',
  );
}
